### ISSUE TITLE
Animation index.html

### ISSUE THREAD

**Issue by enguerran** [unkn0wndfbx/CFA-Website#1]
L'animation apporte une ambiance de fête, mais :

1. elle surcharge les ordinateurs (processeurs)
2. elle ne peut pas être maitrisée par le visiteur

https://github.com/unkn0wndfbx/CFA-Website/blob/d200c03e19de0c8cbc302ddf40e72cd5f6c4a600/index.html#L64-L89 

Je propose 3 actions :
- revoir le besoin en premier lieu de l'animation (et trouver d'autres réponses au besoin)
- si animation alors :
    - prendre en compte `prefers-reduced-motion`
    - proposer un bouton pour la désactiver

**Comment by unkn0wndfbx** [comment]
Pour empêcher la surcharge à cause de l'animation je peux faire en sorte que ça soit fixe et que les bulles aient une position aléatoire fixe à chaque chargement de la page. Parce que si on enlève les bulles le fond est un peu vide.
