### ISSUE TITLE
screenreader issue

### ISSUE THREAD

**Issue by enguerran** [unkn0wndfbx/CFA-Website#2]
Les lecteurs d'écran ne vont pas aimer le background qui répète le mot "Fête".
Soit on l'enlève, soit on le modifie pour qu'il ne soit pris que comme décoration : https://github.com/unkn0wndfbx/CFA-Website/blob/6b82ce7963c566a85173d49df762f9dfba7aff08/about.html#L74-L83

**Comment by unkn0wndfbx** [comment]
Okk, il faut que je trouve un élément de séparation entre les deux sections alors parce que sinon ça fait bizarre.
